include $(MTK_PATH_BUILD)/common.mk
$(call all-modules-src-or-makefile,$(obj),CUSTOM_KERNEL_)
obj-n := dummy.o

# lenovo-sw oujf 2014-05-14 remove spidev for modem begin
#obj-y	+= spidev/
# lenovo-sw oujf 2014-05-14 remove spidev for modem end
